wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/ATL_p.png -O ATL.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/FCB_p.png -O FCB.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/BOS_p.png -O BOS.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/BKN_p.png -O BKN.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/SLA_p.png -O SLA.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/CAN_p.png -O CAN.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/CHA_p.png -O CHA.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/CHI_p.png -O CHI.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/CLE_p.png -O CLE.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/DAL_p.png -O DAL.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/DEN_p.png -O DEN.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/DET_p.png -O DET.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/EST_p.png -O EST.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/GSW_p.png -O GSW.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/MAC_p.png -O MAC.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/HOU_p.png -O HOU.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/IND_p.png -O IND.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/LAC_p.png -O LAC.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/LAL_p.png -O LAL.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/MEM_p.png -O MEM.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/MIA_p.png -O MIA.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/MIL_p.png -O MIL.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/MIN_p.png -O MIN.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/NOP_p.png -O NOP.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/NYK_p.png -O NYK.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/OKC_p.png -O OKC.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/ORL_p.png -O ORL.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/PHI_p.png -O PHI.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/PHX_p.png -O PHX.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/POR_p.png -O POR.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/RMD_p.png -O RMD.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/SAC_p.png -O SAC.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/SAS_p.png -O SAS.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/SDS_p.png -O SDS.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/TOR_p.png -O TOR.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/USA_p.png -O USA.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/USA_p.png -O USA.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/UTA_p.png -O UTA.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/WAS_p.png -O WAS.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/WST_p.png -O WST.png
wget https://neulionms-a.akamaihd.net/nba/player/v7/nba/site/images/teams/WLD_p.png -O WLD.png